//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colora.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Colora.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Value.
        /// </summary>
        public static string ColorEdit_lblColor {
            get {
                return ResourceManager.GetString("ColorEdit_lblColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string ColorEdit_lblComment {
            get {
                return ResourceManager.GetString("ColorEdit_lblComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The given color code is not valid..
        /// </summary>
        public static string ColorEdit_strInvalidColor {
            get {
                return ResourceManager.GetString("ColorEdit_strInvalidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Color.
        /// </summary>
        public static string ColorEdit_Title {
            get {
                return ResourceManager.GetString("ColorEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Global_strCancel {
            get {
                return ResourceManager.GetString("Global_strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the desired key combination.
        /// </summary>
        public static string HotKeyInputWindow_grpHeader {
            get {
                return ResourceManager.GetString("HotKeyInputWindow_grpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Picking Shortcut.
        /// </summary>
        public static string HotKeyInputWindow_Title {
            get {
                return ResourceManager.GetString("HotKeyInputWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to History.
        /// </summary>
        public static string MainWindow_butAddLast {
            get {
                return ResourceManager.GetString("MainWindow_butAddLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Palette.
        /// </summary>
        public static string MainWindow_butAddPalette {
            get {
                return ResourceManager.GetString("MainWindow_butAddPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Data.
        /// </summary>
        public static string MainWindow_grpColorData {
            get {
                return ResourceManager.GetString("MainWindow_grpColorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color History.
        /// </summary>
        public static string MainWindow_grpLatest {
            get {
                return ResourceManager.GetString("MainWindow_grpLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Picker.
        /// </summary>
        public static string MainWindow_grpScreenPicker {
            get {
                return ResourceManager.GetString("MainWindow_grpScreenPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_bout.
        /// </summary>
        public static string MainWindow_menAbout {
            get {
                return ResourceManager.GetString("MainWindow_menAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open _Color Dialog.
        /// </summary>
        public static string MainWindow_menColorDialog {
            get {
                return ResourceManager.GetString("MainWindow_menColorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color _History.
        /// </summary>
        public static string MainWindow_menColorHistory {
            get {
                return ResourceManager.GetString("MainWindow_menColorHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_olors.
        /// </summary>
        public static string MainWindow_menColors {
            get {
                return ResourceManager.GetString("MainWindow_menColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure _Keyboard Shortcut....
        /// </summary>
        public static string MainWindow_menConfigureShortcut {
            get {
                return ResourceManager.GetString("MainWindow_menConfigureShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Color.
        /// </summary>
        public static string MainWindow_menDeleteHistoryItem {
            get {
                return ResourceManager.GetString("MainWindow_menDeleteHistoryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear _History.
        /// </summary>
        public static string MainWindow_menDeleteLatest {
            get {
                return ResourceManager.GetString("MainWindow_menDeleteLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get _Updates.
        /// </summary>
        public static string MainWindow_menGetUpdates {
            get {
                return ResourceManager.GetString("MainWindow_menGetUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Icon Bar.
        /// </summary>
        public static string MainWindow_menIconBar {
            get {
                return ResourceManager.GetString("MainWindow_menIconBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Screen Picker.
        /// </summary>
        public static string MainWindow_menMinimalSize {
            get {
                return ResourceManager.GetString("MainWindow_menMinimalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Palette from History.
        /// </summary>
        public static string MainWindow_menNewPalette {
            get {
                return ResourceManager.GetString("MainWindow_menNewPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string MainWindow_menOptions {
            get {
                return ResourceManager.GetString("MainWindow_menOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Palette Editor.
        /// </summary>
        public static string MainWindow_menPaletteEditor {
            get {
                return ResourceManager.GetString("MainWindow_menPaletteEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick from _Screen.
        /// </summary>
        public static string MainWindow_menPickScreen {
            get {
                return ResourceManager.GetString("MainWindow_menPickScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin on _Top.
        /// </summary>
        public static string MainWindow_menTopmost {
            get {
                return ResourceManager.GetString("MainWindow_menTopmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MainWindow_menView {
            get {
                return ResourceManager.GetString("MainWindow_menView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Clipboard.
        /// </summary>
        public static string MainWindow_strClipboard {
            get {
                return ResourceManager.GetString("MainWindow_strClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More c_olor models.
        /// </summary>
        public static string MainWindow_strColorSettings {
            get {
                return ResourceManager.GetString("MainWindow_strColorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string MainWindow_strCopy {
            get {
                return ResourceManager.GetString("MainWindow_strCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering shortcut &apos;{0}&apos; failed.
        ///This could be caused by another app using the same shortcut..
        /// </summary>
        public static string MainWindow_strHotKeyFailed {
            get {
                return ResourceManager.GetString("MainWindow_strHotKeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No shortcut registered..
        /// </summary>
        public static string MainWindow_strNoShortcut {
            get {
                return ResourceManager.GetString("MainWindow_strNoShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to pick colors from screen..
        /// </summary>
        public static string MainWindow_strShortcut {
            get {
                return ResourceManager.GetString("MainWindow_strShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit Color.
        /// </summary>
        public static string PaletteWindow_menEdit {
            get {
                return ResourceManager.GetString("PaletteWindow_menEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string PaletteWindow_menFile {
            get {
                return ResourceManager.GetString("PaletteWindow_menFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open Palette.
        /// </summary>
        public static string PaletteWindow_menOpen {
            get {
                return ResourceManager.GetString("PaletteWindow_menOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save Palette.
        /// </summary>
        public static string PaletteWindow_menSave {
            get {
                return ResourceManager.GetString("PaletteWindow_menSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected color will be removed from palette..
        /// </summary>
        public static string PaletteWindow_strDelete {
            get {
                return ResourceManager.GetString("PaletteWindow_strDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read palette from specified file.
        ///Error code: .
        /// </summary>
        public static string PaletteWindow_strErrorOpen {
            get {
                return ResourceManager.GetString("PaletteWindow_strErrorOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save palette to specified file.
        ///Error code: .
        /// </summary>
        public static string PaletteWindow_strErrorSave {
            get {
                return ResourceManager.GetString("PaletteWindow_strErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open palette file. File format may be wrong. 
        ///Error code: .
        /// </summary>
        public static string PaletteWindow_strInvalidFormat {
            get {
                return ResourceManager.GetString("PaletteWindow_strInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current color palette is unsaved. Continue?.
        /// </summary>
        public static string PaletteWindow_strNotSaved {
            get {
                return ResourceManager.GetString("PaletteWindow_strNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette Editor.
        /// </summary>
        public static string PaletteWindow_Title {
            get {
                return ResourceManager.GetString("PaletteWindow_Title", resourceCulture);
            }
        }
    }
}
